[versions]
shizuku = "13.1.5"

[libraries]
activity = "androidx.activity:activity:1.10.1"
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.2.1" }
browser = "androidx.browser:browser:1.8.0"
core-i18n = "androidx.core:core-i18n:1.0.0"
core-ktx = "androidx.core:core-ktx:1.16.0"
desugar = "com.android.tools:desugar_jdk_libs:2.1.5"
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = "com.google.firebase:firebase-bom:33.13.0"
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
fragment-ktx = "androidx.fragment:fragment-ktx:1.8.6"
hiddenapibypass = "org.lsposed.hiddenapibypass:hiddenapibypass:6.1"
junit = { group = "junit", name = "junit", version = "4.13.2" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version = "2.8.7" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version = "21.3.0" }
s2-geometry = "com.google.geometry:s2-geometry:2.0.0"
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }
timber = { group = "com.jakewharton.timber", name = "timber", version = "5.0.1" }
work = "androidx.work:work-runtime:2.10.1"

[plugins]
androidApplication = "com.android.application:8.10.0"
firebaseCrashlytics = "com.google.firebase.crashlytics:3.0.3"
googleServices = { id = "com.google.gms.google-services", version = "4.4.2" }
kotlinAndroid = "org.jetbrains.kotlin.android:2.1.20"
gradleVersions = "com.github.ben-manes.versions:0.52.0"
