[versions]
shizuku = "13.1.5"

[libraries]
activity = "androidx.activity:activity:1.11.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.3.0"
browser = "androidx.browser:browser:1.9.0"
core-i18n = "androidx.core:core-i18n:1.0.0"
core-ktx = "androidx.core:core-ktx:1.17.0"
desugar = "com.android.tools:desugar_jdk_libs:2.1.5"
espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
firebase-analytics = "com.google.firebase:firebase-analytics:23.0.0"
firebase-crashlytics-ndk = "com.google.firebase:firebase-crashlytics-ndk:20.0.3"
fragment-ktx = "androidx.fragment:fragment-ktx:1.8.9"
hiddenapibypass = "org.lsposed.hiddenapibypass:hiddenapibypass:6.1"
junit = "junit:junit:4.13.2"
lifecycle-common = "androidx.lifecycle:lifecycle-common:2.9.4"
material = "com.google.android.material:material:1.13.0"
play-services-location = "com.google.android.gms:play-services-location:21.3.0"
s2-geometry = "com.google.geometry:s2-geometry:2.0.0"
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }
timber = "com.jakewharton.timber:timber:5.0.1"
work = "androidx.work:work-runtime:2.11.0"

[plugins]
androidApplication = "com.android.application:8.13.0"
firebaseCrashlytics = "com.google.firebase.crashlytics:3.0.6"
googleServices = "com.google.gms.google-services:4.4.4"
kotlinAndroid = "org.jetbrains.kotlin.android:2.2.21"
gradleVersions = "com.github.ben-manes.versions:0.53.0"
