[versions]
activity = "1.8.1"
agp = "8.3.0-alpha14"
androidx-test-ext-junit = "1.1.5"
browser = "1.7.0"
core = "1.12.0"
crashlytics = "2.9.9"
desugar = "2.0.4"
espresso-core = "3.5.1"
firebase = "32.6.0"
fragment = "1.6.2"
hiddenapibypass = "4.3"
junit = "4.13.2"
kotlin = "1.9.20"
lifecycle = "2.7.0-rc01"
google-services = "4.4.0"
play-services-location = "21.0.1"
timber = "5.0.1"
work = "2.9.0-rc01"
gradle-versions = "0.50.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycle" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
