[versions]
activity = "1.9.2"
agp = "8.7.0"
androidx-test-ext-junit = "1.2.1"
browser = "1.8.0"
core = "1.13.1"
crashlytics = "3.0.2"
desugar = "2.1.2"
espresso-core = "3.6.1"
firebase = "33.4.0"
fragment = "1.8.4"
hiddenapibypass = "4.3"
junit = "4.13.2"
kotlin = "2.0.20"
lifecycle = "2.8.6"
google-services = "4.4.2"
material = "1.12.0"
play-services-location = "21.3.0"
timber = "5.0.1"
work = "2.9.1"
gradle-versions = "0.51.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "hiddenapibypass" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "lifecycle" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
